import {
  ArrowUp,
  BookText,
  Bot,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Loader2,
  Menu,
  Paperclip,
  Search,
  Settings,
  Trash2,
  User,
  X,
} from 'lucide-react';

export const Icons = {
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  check: Check,
  search: Search,
  circle: Circle,
  x: X,
  spinner: Loader2,
  logo: BookText,
  paperClip: Paperclip,
  trash: Trash2,
  send: ArrowUp,
  user: User,
  bot: Bot,
  settings: Settings,
  menu: Menu,
};
