import {
  ArrowUp,
  BookText,
  Bot,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Eye,
  EyeOff,
  Laptop,
  Loader2,
  LogOut,
  Menu,
  Moon,
  Paperclip,
  Search,
  Settings,
  StopCircle,
  SunMedium,
  Trash2,
  Upload,
  User,
  X,
} from 'lucide-react';

export const Icons = {
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  check: Check,
  search: Search,
  circle: Circle,
  x: X,
  eye: Eye,
  eyeOff: EyeOff,
  spinner: Loader2,
  logo: BookText,
  sun: SunMedium,
  laptop: Laptop,
  moon: Moon,
  signout: LogOut,
  upload: Upload,
  paperClip: Paperclip,
  trash: Trash2,
  send: ArrowUp,
  user: User,
  bot: Bot,
  settings: Settings,
  stop: StopCircle,
  menu: Menu,
};
